# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SolutionData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12SolutionData.proto\x12\rgammarecorder\"\xba\x01\n\x0cSolutionData\x12\x14\n\x0c\x63ycle_number\x18\x01 \x01(\x03\x12\x0e\n\x06n_rows\x18\x02 \x01(\r\x12\x0e\n\x06n_cols\x18\x03 \x01(\r\x12\x16\n\x0esolution_array\x18\x04 \x03(\x02\x12 \n\x18\x65lapsed_time_intensities\x18\x05 \x01(\x04\x12\x1d\n\x15\x65lapsed_time_solution\x18\x06 \x01(\x04\x12\x1b\n\x13published_timestamp\x18\x07 \x01(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SolutionData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOLUTIONDATA._serialized_start=38
  _SOLUTIONDATA._serialized_end=224
# @@protoc_insertion_point(module_scope)
